-- Añadir 50 palabras UltraHard (parte 2 de 2 - últimas 25)
INSERT INTO vocabulary (word, translation, example, level) VALUES
('Insipid', 'Insípido, sin sabor', 'The movie was insipid.', 'UltraHard'),
('Fastidious', 'Fastidioso, difícil de complacer', 'He is fastidious about cleanliness.', 'UltraHard'),
('Parsimonious', 'Parsimonioso, frugal', 'His parsimonious nature is known.', 'UltraHard'),
('Recondite', 'Recóndito, oscuro', 'The subject is quite recondite.', 'UltraHard'),
('Sanguine', 'Sanguíneo, optimista', 'She remained sanguine.', 'UltraHard'),
('Trenchant', 'Incisivo, efectivo', 'His trenchant criticism was valid.', 'UltraHard'),
('Vicarious', 'Vicario, a través de otro', 'She had vicarious pleasure.', 'UltraHard'),
('Abstruse', 'Abstruso, difícil', 'The theory is quite abstruse.', 'UltraHard'),
('Bellicose', 'Belicoso, agresivo', 'His bellicose attitude caused conflict.', 'UltraHard'),
('Capricious', 'Caprichoso, cambiante', 'The weather is capricious here.', 'UltraHard'),
('Didactic', 'Didáctico, educativo', 'The didactic tone was helpful.', 'UltraHard'),
('Erudite', 'Erudito, culto', 'The erudite professor impressed us.', 'UltraHard'),
('Fractious', 'Levantisco, irritable', 'The fractious child was difficult.', 'UltraHard'),
('Garrulous', 'Gárrulo, hablador', 'The garrulous neighbor talked endlessly.', 'UltraHard'),
('Inchoate', 'Incipiente, comenzado', 'The plan is still inchoate.', 'UltraHard'),
('Laconic', 'Lacónico, breve', 'His laconic reply said everything.', 'UltraHard'),
('Mordant', 'Mordaz, sarcástico', 'Her mordant wit was famous.', 'UltraHard'),
('Nebulous', 'Nebuloso, vago', 'The plan remains nebulous.', 'UltraHard'),
('Ostensible', 'Ostensible, aparente', 'The ostensible reason was false.', 'UltraHard'),
('Pellucid', 'Translúcido, claro', 'Her pellucid prose is beautiful.', 'UltraHard'),
('Querulous', 'Quejumbroso, quejón', 'His querulous tone annoyed everyone.', 'UltraHard'),
('Redolent', 'Redolente, evocador', 'The smell was redolent of childhood.', 'UltraHard'),
('Sagacious', 'Sagaz, sabio', 'The sagacious leader made wise choices.', 'UltraHard'),
('Taciturn', 'Taciturno, callado', 'He is naturally taciturn.', 'UltraHard'),
('Vapid', 'Insulso, sin interés', 'The conversation was vapid.', 'UltraHard');