-- Añadir 50 palabras UltraHard (parte 1 de 2 - primeras 25)
INSERT INTO vocabulary (word, translation, example, level) VALUES
('Verisimilitude', 'Verosimilitud, apariencia de ser real', 'The story lacks verisimilitude.', 'UltraHard'),
('Idiosyncratic', 'Idiosincrático, peculiar', 'His idiosyncratic behavior is known.', 'UltraHard'),
('Pusillanimous', 'Pusilánime, sin coraje', 'The pusillanimous leader failed.', 'UltraHard'),
('Recalcitrant', 'Recalcitrante, obstinado', 'The recalcitrant student refused.', 'UltraHard'),
('Propinquity', 'Propincuidad, proximidad', 'The propinquity is notable.', 'UltraHard'),
('Lugubrious', 'Lúgubre, triste', 'The lugubrious atmosphere affected all.', 'UltraHard'),
('Perspicuous', 'Perspicuo, fácil de entender', 'Her explanation was perspicuous.', 'UltraHard'),
('Grandiloquent', 'Grandilocuente, pomposo', 'His grandiloquent speech was tedious.', 'UltraHard'),
('Lachrymose', 'Lacrimoso, dado a llorar', 'The lachrymose audience moved me.', 'UltraHard'),
('Mendacious', 'Mendaz, mentiroso', 'The mendacious politician lost trust.', 'UltraHard'),
('Truculent', 'Truculento, agresivo', 'His truculent manner was off-putting.', 'UltraHard'),
('Stentorian', 'Estentóreo, muy fuerte', 'His stentorian voice echoed.', 'UltraHard'),
('Concatenate', 'Concatenar, conectar', 'We need to concatenate these events.', 'UltraHard'),
('Nefarious', 'Nefario, malvado', 'The nefarious plot was discovered.', 'UltraHard'),
('Perspicacity', 'Perspicacia, agudeza mental', 'Her perspicacity impressed everyone.', 'UltraHard'),
('Sesquipedalian', 'Sesquipedal, palabra larga', 'His sesquipedalian vocabulary confused.', 'UltraHard'),
('Defenestration', 'Defenestración, arrojar por ventana', 'The defenestration was shocking.', 'UltraHard'),
('Antediluvian', 'Antediluviano, muy antiguo', 'His antediluvian ideas were obsolete.', 'UltraHard'),
('Execrable', 'Execrable, muy malo', 'The food quality was execrable.', 'UltraHard'),
('Perfidious', 'Pérfido, traicionero', 'His perfidious actions hurt many.', 'UltraHard'),
('Somnolent', 'Somnoliento, que induce sueño', 'The somnolent afternoon made me drowsy.', 'UltraHard'),
('Ubiquitous', 'Ubicuo, en todas partes', 'Smartphones are ubiquitous today.', 'UltraHard'),
('Ephemeral', 'Efímero, de corta duración', 'Fame can be ephemeral.', 'UltraHard'),
('Circumlocution', 'Circunlocución, manera indirecta', 'His circumlocution annoyed listeners.', 'UltraHard'),
('Abnegation', 'Abnegación, renuncia', 'Her abnegation was admirable.', 'UltraHard');