// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbzngxqaambdtkutwpbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiem5neHFhYW1iZHRrdXR3cGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTYwMjMsImV4cCI6MjA3NDQ5MjAyM30.QQe8a2u5XVX4Iph1B_2CodAb75Mgz2FB7x1MxCKqHTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});